### ISSUE TITLE
CPU + GPU

### ISSUE THREAD

**Issue by plalx** [WaltonChain/WaltonWallet_Win_x64#7]
It would be great if we could mine with CPU + GPU concurrently. 

While trying to find a workaround I found that wallet.exe seems to be a modified GETH, but I can't manage to launch two instances because it complains about the port 10240 being already in use. Is there any undocumented flag to configure this port?

**Comment by Robbbbbbbbb** [comment]
Agreed with this; I tried to find a way but could not.

**Comment by ssaip** [comment]
You can fire up a VM and cpu mine there.
From what I saw, gpu mining is not worth it at the moment. It only uses 1 gpu and even that one is not running full speed.

**Comment by plalx** [comment]
This is by design so I'm closing it for now.
